name: Generate Snake

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Platane/snk@master
      with:
        github_user_name: BulletSentence
        gif_out_path: dist/github-snake.gif
        svg_out_path: dist/github-snake.svg
